# Generated by Django 2.2.8 on 2019-12-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_puro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descriptcion',
            new_name='descripcion',
        ),
    ]
